### ISSUE TITLE
Unauthorized / Game not Joinable

### ISSUE THREAD

**Issue by christopherklaus** [martinzuern/cards-offending-mankind#113] opened 2020-07-06 21:17 UTC
Show error page for unauthorized

![image](https://user-images.githubusercontent.com/669707/86645576-ce1eee80-bfde-11ea-9682-08fc3d3aad03.png)

**Comment by christopherklaus** [comment] 2020-07-06 21:18
@martinzuern shouldn't it say that the game has already started or something like that?

**Comment by martinzuern** [comment] 2020-11-25 17:07
Depends on whether or not we want to expose that there is a (valid) game for the given ID

**Comment by martinzuern** [comment] 2020-12-13 17:22
Duplicate of #98

**Closed by martinzuern** 2020-12-13 17:22 UTC
Labels: Backend
